global:
  scrape_interval: 1s
  external_labels:
    monitor: 'devopsage-monitor'

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "orderer"
    static_configs:
      - targets: ["localhost:8443"]
  - job_name: "peer0_org1"
    static_configs:
      - targets: ["localhost:8446"]
  - job_name: "peer0_org2"
    static_configs:
      - targets: ["localhost:8448"]
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8080']
  - job_name: node
    static_configs:
      - targets: ['localhost:9100']
